language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-marionette-mann' ]; then cd .. && eval "mv $currentfolder generator-marionette-mann" && cd generator-marionette-mann; fi

